package org.beiyi.entity.db;

public class AtcBelongTo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private Integer atcLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_parent_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_parent_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcParentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_parent_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private String atcParentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_belong_to.atc_parent_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    private Integer atcParentLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.id
     *
     * @return the value of atc_belong_to.id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.id
     *
     * @param id the value for atc_belong_to.id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_id
     *
     * @return the value of atc_belong_to.atc_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcId() {
        return atcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_id
     *
     * @param atcId the value for atc_belong_to.atc_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcId(String atcId) {
        this.atcId = atcId == null ? null : atcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_name
     *
     * @return the value of atc_belong_to.atc_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcName() {
        return atcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_name
     *
     * @param atcName the value for atc_belong_to.atc_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcName(String atcName) {
        this.atcName = atcName == null ? null : atcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_code
     *
     * @return the value of atc_belong_to.atc_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcCode() {
        return atcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_code
     *
     * @param atcCode the value for atc_belong_to.atc_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcCode(String atcCode) {
        this.atcCode = atcCode == null ? null : atcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_level
     *
     * @return the value of atc_belong_to.atc_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public Integer getAtcLevel() {
        return atcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_level
     *
     * @param atcLevel the value for atc_belong_to.atc_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcLevel(Integer atcLevel) {
        this.atcLevel = atcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_parent_id
     *
     * @return the value of atc_belong_to.atc_parent_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcParentId() {
        return atcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_parent_id
     *
     * @param atcParentId the value for atc_belong_to.atc_parent_id
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcParentId(String atcParentId) {
        this.atcParentId = atcParentId == null ? null : atcParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_parent_name
     *
     * @return the value of atc_belong_to.atc_parent_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcParentName() {
        return atcParentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_parent_name
     *
     * @param atcParentName the value for atc_belong_to.atc_parent_name
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcParentName(String atcParentName) {
        this.atcParentName = atcParentName == null ? null : atcParentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_parent_code
     *
     * @return the value of atc_belong_to.atc_parent_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public String getAtcParentCode() {
        return atcParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_parent_code
     *
     * @param atcParentCode the value for atc_belong_to.atc_parent_code
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcParentCode(String atcParentCode) {
        this.atcParentCode = atcParentCode == null ? null : atcParentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_belong_to.atc_parent_level
     *
     * @return the value of atc_belong_to.atc_parent_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public Integer getAtcParentLevel() {
        return atcParentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_belong_to.atc_parent_level
     *
     * @param atcParentLevel the value for atc_belong_to.atc_parent_level
     *
     * @mbggenerated Thu Jul 05 16:38:38 CST 2018
     */
    public void setAtcParentLevel(Integer atcParentLevel) {
        this.atcParentLevel = atcParentLevel;
    }
}