package org.beiyi.entity.db;

public class AtcConflict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String atcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String atcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String atcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.conflict_atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String conflictAtcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.conflict_atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String conflictAtcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.conflict_atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String conflictAtcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column atc_conflict.level_
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.id
     *
     * @return the value of atc_conflict.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.id
     *
     * @param id the value for atc_conflict.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.atc_id
     *
     * @return the value of atc_conflict.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAtcId() {
        return atcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.atc_id
     *
     * @param atcId the value for atc_conflict.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAtcId(String atcId) {
        this.atcId = atcId == null ? null : atcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.atc_name
     *
     * @return the value of atc_conflict.atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAtcName() {
        return atcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.atc_name
     *
     * @param atcName the value for atc_conflict.atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAtcName(String atcName) {
        this.atcName = atcName == null ? null : atcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.atc_code
     *
     * @return the value of atc_conflict.atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAtcCode() {
        return atcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.atc_code
     *
     * @param atcCode the value for atc_conflict.atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAtcCode(String atcCode) {
        this.atcCode = atcCode == null ? null : atcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.conflict_atc_id
     *
     * @return the value of atc_conflict.conflict_atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getConflictAtcId() {
        return conflictAtcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.conflict_atc_id
     *
     * @param conflictAtcId the value for atc_conflict.conflict_atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setConflictAtcId(String conflictAtcId) {
        this.conflictAtcId = conflictAtcId == null ? null : conflictAtcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.conflict_atc_name
     *
     * @return the value of atc_conflict.conflict_atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getConflictAtcName() {
        return conflictAtcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.conflict_atc_name
     *
     * @param conflictAtcName the value for atc_conflict.conflict_atc_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setConflictAtcName(String conflictAtcName) {
        this.conflictAtcName = conflictAtcName == null ? null : conflictAtcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.conflict_atc_code
     *
     * @return the value of atc_conflict.conflict_atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getConflictAtcCode() {
        return conflictAtcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.conflict_atc_code
     *
     * @param conflictAtcCode the value for atc_conflict.conflict_atc_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setConflictAtcCode(String conflictAtcCode) {
        this.conflictAtcCode = conflictAtcCode == null ? null : conflictAtcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column atc_conflict.level_
     *
     * @return the value of atc_conflict.level_
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column atc_conflict.level_
     *
     * @param level the value for atc_conflict.level_
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}