package org.beiyi.entity.db;

public class AtcCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.id
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.en_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.ch_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String chName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.atc_no
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String atcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.dosage
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.unit
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_atc_code.way_of_taking
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    private String wayOfTaking;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.id
     *
     * @return the value of bysy_atc_code.id
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.id
     *
     * @param id the value for bysy_atc_code.id
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.en_name
     *
     * @return the value of bysy_atc_code.en_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.en_name
     *
     * @param enName the value for bysy_atc_code.en_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.ch_name
     *
     * @return the value of bysy_atc_code.ch_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getChName() {
        return chName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.ch_name
     *
     * @param chName the value for bysy_atc_code.ch_name
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setChName(String chName) {
        this.chName = chName == null ? null : chName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.atc_no
     *
     * @return the value of bysy_atc_code.atc_no
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getAtcNo() {
        return atcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.atc_no
     *
     * @param atcNo the value for bysy_atc_code.atc_no
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setAtcNo(String atcNo) {
        this.atcNo = atcNo == null ? null : atcNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.dosage
     *
     * @return the value of bysy_atc_code.dosage
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.dosage
     *
     * @param dosage the value for bysy_atc_code.dosage
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.unit
     *
     * @return the value of bysy_atc_code.unit
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.unit
     *
     * @param unit the value for bysy_atc_code.unit
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_atc_code.way_of_taking
     *
     * @return the value of bysy_atc_code.way_of_taking
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public String getWayOfTaking() {
        return wayOfTaking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_atc_code.way_of_taking
     *
     * @param wayOfTaking the value for bysy_atc_code.way_of_taking
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    public void setWayOfTaking(String wayOfTaking) {
        this.wayOfTaking = wayOfTaking == null ? null : wayOfTaking.trim();
    }
}