package org.beiyi.entity.db;

public class DiseaseIcd10 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.icd10_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String icd10Code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.id
     *
     * @return the value of disease_icd10.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.id
     *
     * @param id the value for disease_icd10.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.disease_id
     *
     * @return the value of disease_icd10.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.disease_id
     *
     * @param diseaseId the value for disease_icd10.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId == null ? null : diseaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.icd10_code
     *
     * @return the value of disease_icd10.icd10_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getIcd10Code() {
        return icd10Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.icd10_code
     *
     * @param icd10Code the value for disease_icd10.icd10_code
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setIcd10Code(String icd10Code) {
        this.icd10Code = icd10Code == null ? null : icd10Code.trim();
    }
}