package org.beiyi.entity.db;

public class DiseaseIcd10 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.disease_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.disease_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String diseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.icd10_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String icd10Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.icd10_code
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String icd10Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.icd10_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String icd10Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_icd10.icd10_version
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    private String icd10Version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.id
     *
     * @return the value of disease_icd10.id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.id
     *
     * @param id the value for disease_icd10.id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.disease_id
     *
     * @return the value of disease_icd10.disease_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.disease_id
     *
     * @param diseaseId the value for disease_icd10.disease_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId == null ? null : diseaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.disease_name
     *
     * @return the value of disease_icd10.disease_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.disease_name
     *
     * @param diseaseName the value for disease_icd10.disease_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName == null ? null : diseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.icd10_name
     *
     * @return the value of disease_icd10.icd10_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getIcd10Name() {
        return icd10Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.icd10_name
     *
     * @param icd10Name the value for disease_icd10.icd10_name
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setIcd10Name(String icd10Name) {
        this.icd10Name = icd10Name == null ? null : icd10Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.icd10_code
     *
     * @return the value of disease_icd10.icd10_code
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getIcd10Code() {
        return icd10Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.icd10_code
     *
     * @param icd10Code the value for disease_icd10.icd10_code
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setIcd10Code(String icd10Code) {
        this.icd10Code = icd10Code == null ? null : icd10Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.icd10_id
     *
     * @return the value of disease_icd10.icd10_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getIcd10Id() {
        return icd10Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.icd10_id
     *
     * @param icd10Id the value for disease_icd10.icd10_id
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setIcd10Id(String icd10Id) {
        this.icd10Id = icd10Id == null ? null : icd10Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_icd10.icd10_version
     *
     * @return the value of disease_icd10.icd10_version
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public String getIcd10Version() {
        return icd10Version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_icd10.icd10_version
     *
     * @param icd10Version the value for disease_icd10.icd10_version
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    public void setIcd10Version(String icd10Version) {
        this.icd10Version = icd10Version == null ? null : icd10Version.trim();
    }
}