package org.beiyi.entity.db;

public class Disease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.alias_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String aliasName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.id
     *
     * @return the value of disease.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.id
     *
     * @param id the value for disease.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.name
     *
     * @return the value of disease.name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.name
     *
     * @param name the value for disease.name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.alias_name
     *
     * @return the value of disease.alias_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.alias_name
     *
     * @param aliasName the value for disease.alias_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }
}