package org.beiyi.entity.db;

public class Icd10 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_icd10.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_icd10.name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_icd10.code
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_icd10.level
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_icd10.version
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_icd10.id
     *
     * @return the value of bysy_icd10.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_icd10.id
     *
     * @param id the value for bysy_icd10.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_icd10.name
     *
     * @return the value of bysy_icd10.name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_icd10.name
     *
     * @param name the value for bysy_icd10.name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_icd10.code
     *
     * @return the value of bysy_icd10.code
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_icd10.code
     *
     * @param code the value for bysy_icd10.code
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_icd10.level
     *
     * @return the value of bysy_icd10.level
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_icd10.level
     *
     * @param level the value for bysy_icd10.level
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_icd10.version
     *
     * @return the value of bysy_icd10.version
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_icd10.version
     *
     * @param version the value for bysy_icd10.version
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}