package org.beiyi.entity.db;

public class IndicationTherapeuticRegimen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indication_therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indication_therapeutic_regimen.indication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String indicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indication_therapeutic_regimen.therapeutic_regimen_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String therapeuticRegimenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indication_therapeutic_regimen.id
     *
     * @return the value of indication_therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indication_therapeutic_regimen.id
     *
     * @param id the value for indication_therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indication_therapeutic_regimen.indication_id
     *
     * @return the value of indication_therapeutic_regimen.indication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getIndicationId() {
        return indicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indication_therapeutic_regimen.indication_id
     *
     * @param indicationId the value for indication_therapeutic_regimen.indication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setIndicationId(String indicationId) {
        this.indicationId = indicationId == null ? null : indicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indication_therapeutic_regimen.therapeutic_regimen_id
     *
     * @return the value of indication_therapeutic_regimen.therapeutic_regimen_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getTherapeuticRegimenId() {
        return therapeuticRegimenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indication_therapeutic_regimen.therapeutic_regimen_id
     *
     * @param therapeuticRegimenId the value for indication_therapeutic_regimen.therapeutic_regimen_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setTherapeuticRegimenId(String therapeuticRegimenId) {
        this.therapeuticRegimenId = therapeuticRegimenId == null ? null : therapeuticRegimenId.trim();
    }
}