package org.beiyi.entity.db;

public class InstructionContraindication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.contraindication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String contraindicationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.id
     *
     * @return the value of instruction_contraindication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.id
     *
     * @param id the value for instruction_contraindication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.instruction_id
     *
     * @return the value of instruction_contraindication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.instruction_id
     *
     * @param instructionId the value for instruction_contraindication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.contraindication_id
     *
     * @return the value of instruction_contraindication.contraindication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getContraindicationId() {
        return contraindicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.contraindication_id
     *
     * @param contraindicationId the value for instruction_contraindication.contraindication_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setContraindicationId(String contraindicationId) {
        this.contraindicationId = contraindicationId == null ? null : contraindicationId.trim();
    }
}