package org.beiyi.entity.db;

public class InstructionIndication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.instruction_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.indication_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String indicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.indication_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String indicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.indication_alias_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String indicationAliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.common_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.commodity_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    private String commodityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.id
     *
     * @return the value of instruction_indication.id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.id
     *
     * @param id the value for instruction_indication.id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.instruction_id
     *
     * @return the value of instruction_indication.instruction_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.instruction_id
     *
     * @param instructionId the value for instruction_indication.instruction_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.indication_id
     *
     * @return the value of instruction_indication.indication_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getIndicationId() {
        return indicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.indication_id
     *
     * @param indicationId the value for instruction_indication.indication_id
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setIndicationId(String indicationId) {
        this.indicationId = indicationId == null ? null : indicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.indication_name
     *
     * @return the value of instruction_indication.indication_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getIndicationName() {
        return indicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.indication_name
     *
     * @param indicationName the value for instruction_indication.indication_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setIndicationName(String indicationName) {
        this.indicationName = indicationName == null ? null : indicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.indication_alias_name
     *
     * @return the value of instruction_indication.indication_alias_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getIndicationAliasName() {
        return indicationAliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.indication_alias_name
     *
     * @param indicationAliasName the value for instruction_indication.indication_alias_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setIndicationAliasName(String indicationAliasName) {
        this.indicationAliasName = indicationAliasName == null ? null : indicationAliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.common_name
     *
     * @return the value of instruction_indication.common_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.common_name
     *
     * @param commonName the value for instruction_indication.common_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.commodity_name
     *
     * @return the value of instruction_indication.commodity_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.commodity_name
     *
     * @param commodityName the value for instruction_indication.commodity_name
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }
}