package org.beiyi.entity.db;

public class InstructionIndication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_indication.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String diseaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.id
     *
     * @return the value of instruction_indication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.id
     *
     * @param id the value for instruction_indication.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.instruction_id
     *
     * @return the value of instruction_indication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.instruction_id
     *
     * @param instructionId the value for instruction_indication.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_indication.disease_id
     *
     * @return the value of instruction_indication.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_indication.disease_id
     *
     * @param diseaseId the value for instruction_indication.disease_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDiseaseId(String diseaseId) {
        this.diseaseId = diseaseId == null ? null : diseaseId.trim();
    }
}