package org.beiyi.entity.db;

public class InstructionContraindication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.instruction_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.contraindication_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String contraindicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.disease_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String diseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.disease_alias_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String diseaseAliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.common_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_contraindication.commodity_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    private String commodityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.id
     *
     * @return the value of instruction_contraindication.id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.id
     *
     * @param id the value for instruction_contraindication.id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.instruction_id
     *
     * @return the value of instruction_contraindication.instruction_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.instruction_id
     *
     * @param instructionId the value for instruction_contraindication.instruction_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.contraindication_id
     *
     * @return the value of instruction_contraindication.contraindication_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getContraindicationId() {
        return contraindicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.contraindication_id
     *
     * @param contraindicationId the value for instruction_contraindication.contraindication_id
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setContraindicationId(String contraindicationId) {
        this.contraindicationId = contraindicationId == null ? null : contraindicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.disease_name
     *
     * @return the value of instruction_contraindication.disease_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.disease_name
     *
     * @param diseaseName the value for instruction_contraindication.disease_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName == null ? null : diseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.disease_alias_name
     *
     * @return the value of instruction_contraindication.disease_alias_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getDiseaseAliasName() {
        return diseaseAliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.disease_alias_name
     *
     * @param diseaseAliasName the value for instruction_contraindication.disease_alias_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setDiseaseAliasName(String diseaseAliasName) {
        this.diseaseAliasName = diseaseAliasName == null ? null : diseaseAliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.common_name
     *
     * @return the value of instruction_contraindication.common_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.common_name
     *
     * @param commonName the value for instruction_contraindication.common_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_contraindication.commodity_name
     *
     * @return the value of instruction_contraindication.commodity_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_contraindication.commodity_name
     *
     * @param commodityName the value for instruction_contraindication.commodity_name
     *
     * @mbggenerated Thu Jul 05 17:04:13 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }
}