package org.beiyi.entity.db;

public class InstructionComponentAtc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component_atc.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component_atc.component_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String componentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component_atc.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String componentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component_atc.atc_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String atcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component_atc.atc_no
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String atcNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component_atc.id
     *
     * @return the value of instruction_component_atc.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component_atc.id
     *
     * @param id the value for instruction_component_atc.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component_atc.component_id
     *
     * @return the value of instruction_component_atc.component_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component_atc.component_id
     *
     * @param componentId the value for instruction_component_atc.component_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setComponentId(String componentId) {
        this.componentId = componentId == null ? null : componentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component_atc.component_name
     *
     * @return the value of instruction_component_atc.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component_atc.component_name
     *
     * @param componentName the value for instruction_component_atc.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component_atc.atc_id
     *
     * @return the value of instruction_component_atc.atc_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getAtcId() {
        return atcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component_atc.atc_id
     *
     * @param atcId the value for instruction_component_atc.atc_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setAtcId(String atcId) {
        this.atcId = atcId == null ? null : atcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component_atc.atc_no
     *
     * @return the value of instruction_component_atc.atc_no
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getAtcNo() {
        return atcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component_atc.atc_no
     *
     * @param atcNo the value for instruction_component_atc.atc_no
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setAtcNo(String atcNo) {
        this.atcNo = atcNo == null ? null : atcNo.trim();
    }
}