package org.beiyi.entity.db;

public class InstructionsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.instruction_id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.common_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.commodity_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.combination_standard_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String combinationStandardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.category
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_category.last_update_time
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    private String lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.id
     *
     * @return the value of instructions_category.id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.id
     *
     * @param id the value for instructions_category.id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.instruction_id
     *
     * @return the value of instructions_category.instruction_id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.instruction_id
     *
     * @param instructionId the value for instructions_category.instruction_id
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.common_name
     *
     * @return the value of instructions_category.common_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.common_name
     *
     * @param commonName the value for instructions_category.common_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.commodity_name
     *
     * @return the value of instructions_category.commodity_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.commodity_name
     *
     * @param commodityName the value for instructions_category.commodity_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.combination_standard_name
     *
     * @return the value of instructions_category.combination_standard_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getCombinationStandardName() {
        return combinationStandardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.combination_standard_name
     *
     * @param combinationStandardName the value for instructions_category.combination_standard_name
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setCombinationStandardName(String combinationStandardName) {
        this.combinationStandardName = combinationStandardName == null ? null : combinationStandardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.category
     *
     * @return the value of instructions_category.category
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.category
     *
     * @param category the value for instructions_category.category
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_category.last_update_time
     *
     * @return the value of instructions_category.last_update_time
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_category.last_update_time
     *
     * @param lastUpdateTime the value for instructions_category.last_update_time
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime == null ? null : lastUpdateTime.trim();
    }
}