package org.beiyi.entity.db;

public class InstructionComponent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.component_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String componentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String atcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.accessories_flag
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private Integer accessoriesFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.id
     *
     * @return the value of instruction_component.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.id
     *
     * @param id the value for instruction_component.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.instruction_id
     *
     * @return the value of instruction_component.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.instruction_id
     *
     * @param instructionId the value for instruction_component.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.component_name
     *
     * @return the value of instruction_component.component_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.component_name
     *
     * @param componentName the value for instruction_component.component_name
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.atc_id
     *
     * @return the value of instruction_component.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAtcId() {
        return atcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.atc_id
     *
     * @param atcId the value for instruction_component.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAtcId(String atcId) {
        this.atcId = atcId == null ? null : atcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.accessories_flag
     *
     * @return the value of instruction_component.accessories_flag
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public Integer getAccessoriesFlag() {
        return accessoriesFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.accessories_flag
     *
     * @param accessoriesFlag the value for instruction_component.accessories_flag
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAccessoriesFlag(Integer accessoriesFlag) {
        this.accessoriesFlag = accessoriesFlag;
    }
}