package org.beiyi.entity.db;

public class Instructions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.tongYongName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String tongyongname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.shangPinName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String shangpinname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.enName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String enname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.preparation
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String preparation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.description
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.specification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.classification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.otc
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private Integer otc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.standard
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.approveCode
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String approvecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.approveDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String approvedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.modifyDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.source
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.id
     *
     * @return the value of instructions.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.id
     *
     * @param id the value for instructions.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.tongYongName
     *
     * @return the value of instructions.tongYongName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getTongyongname() {
        return tongyongname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.tongYongName
     *
     * @param tongyongname the value for instructions.tongYongName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setTongyongname(String tongyongname) {
        this.tongyongname = tongyongname == null ? null : tongyongname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.shangPinName
     *
     * @return the value of instructions.shangPinName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getShangpinname() {
        return shangpinname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.shangPinName
     *
     * @param shangpinname the value for instructions.shangPinName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setShangpinname(String shangpinname) {
        this.shangpinname = shangpinname == null ? null : shangpinname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.enName
     *
     * @return the value of instructions.enName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.enName
     *
     * @param enname the value for instructions.enName
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setEnname(String enname) {
        this.enname = enname == null ? null : enname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.preparation
     *
     * @return the value of instructions.preparation
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getPreparation() {
        return preparation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.preparation
     *
     * @param preparation the value for instructions.preparation
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setPreparation(String preparation) {
        this.preparation = preparation == null ? null : preparation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.description
     *
     * @return the value of instructions.description
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.description
     *
     * @param description the value for instructions.description
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.specification
     *
     * @return the value of instructions.specification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.specification
     *
     * @param specification the value for instructions.specification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.classification
     *
     * @return the value of instructions.classification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.classification
     *
     * @param classification the value for instructions.classification
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.otc
     *
     * @return the value of instructions.otc
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public Integer getOtc() {
        return otc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.otc
     *
     * @param otc the value for instructions.otc
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setOtc(Integer otc) {
        this.otc = otc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.standard
     *
     * @return the value of instructions.standard
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.standard
     *
     * @param standard the value for instructions.standard
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.approveCode
     *
     * @return the value of instructions.approveCode
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getApprovecode() {
        return approvecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.approveCode
     *
     * @param approvecode the value for instructions.approveCode
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setApprovecode(String approvecode) {
        this.approvecode = approvecode == null ? null : approvecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.approveDate
     *
     * @return the value of instructions.approveDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getApprovedate() {
        return approvedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.approveDate
     *
     * @param approvedate the value for instructions.approveDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setApprovedate(String approvedate) {
        this.approvedate = approvedate == null ? null : approvedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.modifyDate
     *
     * @return the value of instructions.modifyDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.modifyDate
     *
     * @param modifydate the value for instructions.modifyDate
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setModifydate(String modifydate) {
        this.modifydate = modifydate == null ? null : modifydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.source
     *
     * @return the value of instructions.source
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.source
     *
     * @param source the value for instructions.source
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
}