package org.beiyi.entity.db;

public class InstructionsAtc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_atc.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_atc.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_atc.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String atcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_atc.id
     *
     * @return the value of instructions_atc.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_atc.id
     *
     * @param id the value for instructions_atc.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_atc.instruction_id
     *
     * @return the value of instructions_atc.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_atc.instruction_id
     *
     * @param instructionId the value for instructions_atc.instruction_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_atc.atc_id
     *
     * @return the value of instructions_atc.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getAtcId() {
        return atcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_atc.atc_id
     *
     * @param atcId the value for instructions_atc.atc_id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setAtcId(String atcId) {
        this.atcId = atcId == null ? null : atcId.trim();
    }
}