package org.beiyi.entity.db;

public class InstructionComponent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.instruction_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String instructionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String componentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.accessories_flag
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private Integer accessoriesFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.component_unit
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String componentUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.commodity_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.common_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruction_component.component
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    private String component;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.id
     *
     * @return the value of instruction_component.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.id
     *
     * @param id the value for instruction_component.id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.instruction_id
     *
     * @return the value of instruction_component.instruction_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getInstructionId() {
        return instructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.instruction_id
     *
     * @param instructionId the value for instruction_component.instruction_id
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setInstructionId(String instructionId) {
        this.instructionId = instructionId == null ? null : instructionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.component_name
     *
     * @return the value of instruction_component.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.component_name
     *
     * @param componentName the value for instruction_component.component_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.accessories_flag
     *
     * @return the value of instruction_component.accessories_flag
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public Integer getAccessoriesFlag() {
        return accessoriesFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.accessories_flag
     *
     * @param accessoriesFlag the value for instruction_component.accessories_flag
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setAccessoriesFlag(Integer accessoriesFlag) {
        this.accessoriesFlag = accessoriesFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.component_unit
     *
     * @return the value of instruction_component.component_unit
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getComponentUnit() {
        return componentUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.component_unit
     *
     * @param componentUnit the value for instruction_component.component_unit
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setComponentUnit(String componentUnit) {
        this.componentUnit = componentUnit == null ? null : componentUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.commodity_name
     *
     * @return the value of instruction_component.commodity_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.commodity_name
     *
     * @param commodityName the value for instruction_component.commodity_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.common_name
     *
     * @return the value of instruction_component.common_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.common_name
     *
     * @param commonName the value for instruction_component.common_name
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruction_component.component
     *
     * @return the value of instruction_component.component
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruction_component.component
     *
     * @param component the value for instruction_component.component
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }
}