package org.beiyi.entity.db;

public class Instructions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.id
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.common_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.commodity_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.en_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.pack
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String pack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.preparation
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String preparation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.description
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.specification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.classification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.otc
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private Integer otc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.standard
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.approve_code
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String approveCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.approve_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String approveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.modify_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.company_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.period
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.source
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions.update_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.id
     *
     * @return the value of instructions.id
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.id
     *
     * @param id the value for instructions.id
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.common_name
     *
     * @return the value of instructions.common_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.common_name
     *
     * @param commonName the value for instructions.common_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.commodity_name
     *
     * @return the value of instructions.commodity_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.commodity_name
     *
     * @param commodityName the value for instructions.commodity_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.en_name
     *
     * @return the value of instructions.en_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.en_name
     *
     * @param enName the value for instructions.en_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.pack
     *
     * @return the value of instructions.pack
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getPack() {
        return pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.pack
     *
     * @param pack the value for instructions.pack
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setPack(String pack) {
        this.pack = pack == null ? null : pack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.preparation
     *
     * @return the value of instructions.preparation
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getPreparation() {
        return preparation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.preparation
     *
     * @param preparation the value for instructions.preparation
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setPreparation(String preparation) {
        this.preparation = preparation == null ? null : preparation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.description
     *
     * @return the value of instructions.description
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.description
     *
     * @param description the value for instructions.description
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.specification
     *
     * @return the value of instructions.specification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.specification
     *
     * @param specification the value for instructions.specification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.classification
     *
     * @return the value of instructions.classification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.classification
     *
     * @param classification the value for instructions.classification
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.otc
     *
     * @return the value of instructions.otc
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public Integer getOtc() {
        return otc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.otc
     *
     * @param otc the value for instructions.otc
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setOtc(Integer otc) {
        this.otc = otc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.standard
     *
     * @return the value of instructions.standard
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.standard
     *
     * @param standard the value for instructions.standard
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.approve_code
     *
     * @return the value of instructions.approve_code
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getApproveCode() {
        return approveCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.approve_code
     *
     * @param approveCode the value for instructions.approve_code
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setApproveCode(String approveCode) {
        this.approveCode = approveCode == null ? null : approveCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.approve_date
     *
     * @return the value of instructions.approve_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.approve_date
     *
     * @param approveDate the value for instructions.approve_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setApproveDate(String approveDate) {
        this.approveDate = approveDate == null ? null : approveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.modify_date
     *
     * @return the value of instructions.modify_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.modify_date
     *
     * @param modifyDate the value for instructions.modify_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.company_name
     *
     * @return the value of instructions.company_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.company_name
     *
     * @param companyName the value for instructions.company_name
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.period
     *
     * @return the value of instructions.period
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.period
     *
     * @param period the value for instructions.period
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.source
     *
     * @return the value of instructions.source
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.source
     *
     * @param source the value for instructions.source
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions.update_date
     *
     * @return the value of instructions.update_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions.update_date
     *
     * @param updateDate the value for instructions.update_date
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }
}