package org.beiyi.entity.db;

public class InstructionsCrowd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.instructions_id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String instructionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.common_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String commonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.commodity_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.age_range_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String ageRangeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.sex_limit_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private Integer sexLimitLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.symptom_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String symptomLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.forbidden_flag
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private Integer forbiddenFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructions_crowd.last_update_date
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    private String lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.id
     *
     * @return the value of instructions_crowd.id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.id
     *
     * @param id the value for instructions_crowd.id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.instructions_id
     *
     * @return the value of instructions_crowd.instructions_id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getInstructionsId() {
        return instructionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.instructions_id
     *
     * @param instructionsId the value for instructions_crowd.instructions_id
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setInstructionsId(String instructionsId) {
        this.instructionsId = instructionsId == null ? null : instructionsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.common_name
     *
     * @return the value of instructions_crowd.common_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.common_name
     *
     * @param commonName the value for instructions_crowd.common_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.commodity_name
     *
     * @return the value of instructions_crowd.commodity_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.commodity_name
     *
     * @param commodityName the value for instructions_crowd.commodity_name
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.age_range_limit
     *
     * @return the value of instructions_crowd.age_range_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getAgeRangeLimit() {
        return ageRangeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.age_range_limit
     *
     * @param ageRangeLimit the value for instructions_crowd.age_range_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setAgeRangeLimit(String ageRangeLimit) {
        this.ageRangeLimit = ageRangeLimit == null ? null : ageRangeLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.sex_limit_limit
     *
     * @return the value of instructions_crowd.sex_limit_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public Integer getSexLimitLimit() {
        return sexLimitLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.sex_limit_limit
     *
     * @param sexLimitLimit the value for instructions_crowd.sex_limit_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setSexLimitLimit(Integer sexLimitLimit) {
        this.sexLimitLimit = sexLimitLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.symptom_limit
     *
     * @return the value of instructions_crowd.symptom_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getSymptomLimit() {
        return symptomLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.symptom_limit
     *
     * @param symptomLimit the value for instructions_crowd.symptom_limit
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setSymptomLimit(String symptomLimit) {
        this.symptomLimit = symptomLimit == null ? null : symptomLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.forbidden_flag
     *
     * @return the value of instructions_crowd.forbidden_flag
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public Integer getForbiddenFlag() {
        return forbiddenFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.forbidden_flag
     *
     * @param forbiddenFlag the value for instructions_crowd.forbidden_flag
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setForbiddenFlag(Integer forbiddenFlag) {
        this.forbiddenFlag = forbiddenFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructions_crowd.last_update_date
     *
     * @return the value of instructions_crowd.last_update_date
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public String getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructions_crowd.last_update_date
     *
     * @param lastUpdateDate the value for instructions_crowd.last_update_date
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    public void setLastUpdateDate(String lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate == null ? null : lastUpdateDate.trim();
    }
}