package org.beiyi.entity.db;

public class PrescriptionVerifyRecordHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String prescriptionVerifyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String prescriptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_time
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String verifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_progress
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private Integer verifyProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String verifyProgressDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_person
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String verifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String verifyPersonUniqueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.dispose_suggest
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    private String disposeSuggest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.id
     *
     * @return the value of prescription_verify_record_history.id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.id
     *
     * @param id the value for prescription_verify_record_history.id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @return the value of prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getPrescriptionVerifyRecordId() {
        return prescriptionVerifyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @param prescriptionVerifyRecordId the value for prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setPrescriptionVerifyRecordId(String prescriptionVerifyRecordId) {
        this.prescriptionVerifyRecordId = prescriptionVerifyRecordId == null ? null : prescriptionVerifyRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.prescription_no
     *
     * @return the value of prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getPrescriptionNo() {
        return prescriptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.prescription_no
     *
     * @param prescriptionNo the value for prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setPrescriptionNo(String prescriptionNo) {
        this.prescriptionNo = prescriptionNo == null ? null : prescriptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_time
     *
     * @return the value of prescription_verify_record_history.verify_time
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_time
     *
     * @param verifyTime the value for prescription_verify_record_history.verify_time
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setVerifyTime(String verifyTime) {
        this.verifyTime = verifyTime == null ? null : verifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_progress
     *
     * @return the value of prescription_verify_record_history.verify_progress
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public Integer getVerifyProgress() {
        return verifyProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_progress
     *
     * @param verifyProgress the value for prescription_verify_record_history.verify_progress
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setVerifyProgress(Integer verifyProgress) {
        this.verifyProgress = verifyProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_progress_desc
     *
     * @return the value of prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getVerifyProgressDesc() {
        return verifyProgressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_progress_desc
     *
     * @param verifyProgressDesc the value for prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setVerifyProgressDesc(String verifyProgressDesc) {
        this.verifyProgressDesc = verifyProgressDesc == null ? null : verifyProgressDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_person
     *
     * @return the value of prescription_verify_record_history.verify_person
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getVerifyPerson() {
        return verifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_person
     *
     * @param verifyPerson the value for prescription_verify_record_history.verify_person
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setVerifyPerson(String verifyPerson) {
        this.verifyPerson = verifyPerson == null ? null : verifyPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @return the value of prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getVerifyPersonUniqueNo() {
        return verifyPersonUniqueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @param verifyPersonUniqueNo the value for prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setVerifyPersonUniqueNo(String verifyPersonUniqueNo) {
        this.verifyPersonUniqueNo = verifyPersonUniqueNo == null ? null : verifyPersonUniqueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.dispose_suggest
     *
     * @return the value of prescription_verify_record_history.dispose_suggest
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public String getDisposeSuggest() {
        return disposeSuggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.dispose_suggest
     *
     * @param disposeSuggest the value for prescription_verify_record_history.dispose_suggest
     *
     * @mbggenerated Fri Jul 27 17:20:35 CST 2018
     */
    public void setDisposeSuggest(String disposeSuggest) {
        this.disposeSuggest = disposeSuggest == null ? null : disposeSuggest.trim();
    }
}