package org.beiyi.entity.db;

public class PrescriptionVerifyRecordHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String prescriptionVerifyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String prescriptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_time
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String verifyTime;

    /**
     *  0 : 机器未审核    1 : 机器已审核-未通过   2: 机器已审核 - 已通过  3: 医师强制提交 - 药师未审核  4: 医师强制提交 - 药师已审核 - 未通过  5: 医师强制提交 - 药师已审核 - 已通过
     */
    private Integer verifyProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String verifyProgressDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_person
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String verifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    private String verifyPersonUniqueNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.id
     *
     * @return the value of prescription_verify_record_history.id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.id
     *
     * @param id the value for prescription_verify_record_history.id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @return the value of prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getPrescriptionVerifyRecordId() {
        return prescriptionVerifyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.prescription_verify_record_id
     *
     * @param prescriptionVerifyRecordId the value for prescription_verify_record_history.prescription_verify_record_id
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setPrescriptionVerifyRecordId(String prescriptionVerifyRecordId) {
        this.prescriptionVerifyRecordId = prescriptionVerifyRecordId == null ? null : prescriptionVerifyRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.prescription_no
     *
     * @return the value of prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getPrescriptionNo() {
        return prescriptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.prescription_no
     *
     * @param prescriptionNo the value for prescription_verify_record_history.prescription_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setPrescriptionNo(String prescriptionNo) {
        this.prescriptionNo = prescriptionNo == null ? null : prescriptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_time
     *
     * @return the value of prescription_verify_record_history.verify_time
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_time
     *
     * @param verifyTime the value for prescription_verify_record_history.verify_time
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setVerifyTime(String verifyTime) {
        this.verifyTime = verifyTime == null ? null : verifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_progress
     *
     * @return the value of prescription_verify_record_history.verify_progress
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public Integer getVerifyProgress() {
        return verifyProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_progress
     *
     * @param verifyProgress the value for prescription_verify_record_history.verify_progress
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setVerifyProgress(Integer verifyProgress) {
        this.verifyProgress = verifyProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_progress_desc
     *
     * @return the value of prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getVerifyProgressDesc() {
        return verifyProgressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_progress_desc
     *
     * @param verifyProgressDesc the value for prescription_verify_record_history.verify_progress_desc
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setVerifyProgressDesc(String verifyProgressDesc) {
        this.verifyProgressDesc = verifyProgressDesc == null ? null : verifyProgressDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_person
     *
     * @return the value of prescription_verify_record_history.verify_person
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getVerifyPerson() {
        return verifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_person
     *
     * @param verifyPerson the value for prescription_verify_record_history.verify_person
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setVerifyPerson(String verifyPerson) {
        this.verifyPerson = verifyPerson == null ? null : verifyPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @return the value of prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public String getVerifyPersonUniqueNo() {
        return verifyPersonUniqueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_history.verify_person_unique_no
     *
     * @param verifyPersonUniqueNo the value for prescription_verify_record_history.verify_person_unique_no
     *
     * @mbggenerated Tue Jul 24 15:51:39 CST 2018
     */
    public void setVerifyPersonUniqueNo(String verifyPersonUniqueNo) {
        this.verifyPersonUniqueNo = verifyPersonUniqueNo == null ? null : verifyPersonUniqueNo.trim();
    }
}