package org.beiyi.entity.db;

public class PrescriptionVerifyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.id
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.hospital
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.prescription_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String prescriptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.patient_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String patientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.patient_name
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.patient_sex
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String patientSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.patient_born_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String patientBornDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.reimbursement
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String reimbursement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.patient_crowd
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String patientCrowd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.vis_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String visDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.vis_section
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String visSection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.vis_section_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String visSectionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.doctor_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String doctorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.medical_insurance_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String medicalInsuranceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.diagnosis_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String diagnosisNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.diagnosis
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String diagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.diagnosis_desc
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String diagnosisDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.verify_result
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String verifyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.upload_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record.verify_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    private String verifyTime;

    /**
     * 0 待审核         1机器审核-通过          2机器审核-未通过         3人工审核-待审       4人工审核-已审
     */
    private Integer verifyProgress;
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.id
     *
     * @return the value of prescription_verify_record.id
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.id
     *
     * @param id the value for prescription_verify_record.id
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.hospital
     *
     * @return the value of prescription_verify_record.hospital
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.hospital
     *
     * @param hospital the value for prescription_verify_record.hospital
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.prescription_no
     *
     * @return the value of prescription_verify_record.prescription_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPrescriptionNo() {
        return prescriptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.prescription_no
     *
     * @param prescriptionNo the value for prescription_verify_record.prescription_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPrescriptionNo(String prescriptionNo) {
        this.prescriptionNo = prescriptionNo == null ? null : prescriptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.patient_no
     *
     * @return the value of prescription_verify_record.patient_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPatientNo() {
        return patientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.patient_no
     *
     * @param patientNo the value for prescription_verify_record.patient_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo == null ? null : patientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.patient_name
     *
     * @return the value of prescription_verify_record.patient_name
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.patient_name
     *
     * @param patientName the value for prescription_verify_record.patient_name
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.patient_sex
     *
     * @return the value of prescription_verify_record.patient_sex
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.patient_sex
     *
     * @param patientSex the value for prescription_verify_record.patient_sex
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex == null ? null : patientSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.patient_born_date
     *
     * @return the value of prescription_verify_record.patient_born_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPatientBornDate() {
        return patientBornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.patient_born_date
     *
     * @param patientBornDate the value for prescription_verify_record.patient_born_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPatientBornDate(String patientBornDate) {
        this.patientBornDate = patientBornDate == null ? null : patientBornDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.reimbursement
     *
     * @return the value of prescription_verify_record.reimbursement
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getReimbursement() {
        return reimbursement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.reimbursement
     *
     * @param reimbursement the value for prescription_verify_record.reimbursement
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setReimbursement(String reimbursement) {
        this.reimbursement = reimbursement == null ? null : reimbursement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.patient_crowd
     *
     * @return the value of prescription_verify_record.patient_crowd
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getPatientCrowd() {
        return patientCrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.patient_crowd
     *
     * @param patientCrowd the value for prescription_verify_record.patient_crowd
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setPatientCrowd(String patientCrowd) {
        this.patientCrowd = patientCrowd == null ? null : patientCrowd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.vis_date
     *
     * @return the value of prescription_verify_record.vis_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getVisDate() {
        return visDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.vis_date
     *
     * @param visDate the value for prescription_verify_record.vis_date
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVisDate(String visDate) {
        this.visDate = visDate == null ? null : visDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.vis_section
     *
     * @return the value of prescription_verify_record.vis_section
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getVisSection() {
        return visSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.vis_section
     *
     * @param visSection the value for prescription_verify_record.vis_section
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVisSection(String visSection) {
        this.visSection = visSection == null ? null : visSection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.vis_section_no
     *
     * @return the value of prescription_verify_record.vis_section_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getVisSectionNo() {
        return visSectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.vis_section_no
     *
     * @param visSectionNo the value for prescription_verify_record.vis_section_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVisSectionNo(String visSectionNo) {
        this.visSectionNo = visSectionNo == null ? null : visSectionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.doctor_no
     *
     * @return the value of prescription_verify_record.doctor_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getDoctorNo() {
        return doctorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.doctor_no
     *
     * @param doctorNo the value for prescription_verify_record.doctor_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setDoctorNo(String doctorNo) {
        this.doctorNo = doctorNo == null ? null : doctorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.medical_insurance_no
     *
     * @return the value of prescription_verify_record.medical_insurance_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getMedicalInsuranceNo() {
        return medicalInsuranceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.medical_insurance_no
     *
     * @param medicalInsuranceNo the value for prescription_verify_record.medical_insurance_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setMedicalInsuranceNo(String medicalInsuranceNo) {
        this.medicalInsuranceNo = medicalInsuranceNo == null ? null : medicalInsuranceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.diagnosis_no
     *
     * @return the value of prescription_verify_record.diagnosis_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getDiagnosisNo() {
        return diagnosisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.diagnosis_no
     *
     * @param diagnosisNo the value for prescription_verify_record.diagnosis_no
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setDiagnosisNo(String diagnosisNo) {
        this.diagnosisNo = diagnosisNo == null ? null : diagnosisNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.diagnosis
     *
     * @return the value of prescription_verify_record.diagnosis
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getDiagnosis() {
        return diagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.diagnosis
     *
     * @param diagnosis the value for prescription_verify_record.diagnosis
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis == null ? null : diagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.diagnosis_desc
     *
     * @return the value of prescription_verify_record.diagnosis_desc
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getDiagnosisDesc() {
        return diagnosisDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.diagnosis_desc
     *
     * @param diagnosisDesc the value for prescription_verify_record.diagnosis_desc
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setDiagnosisDesc(String diagnosisDesc) {
        this.diagnosisDesc = diagnosisDesc == null ? null : diagnosisDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.verify_result
     *
     * @return the value of prescription_verify_record.verify_result
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getVerifyResult() {
        return verifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.verify_result
     *
     * @param verifyResult the value for prescription_verify_record.verify_result
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVerifyResult(String verifyResult) {
        this.verifyResult = verifyResult == null ? null : verifyResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.upload_time
     *
     * @return the value of prescription_verify_record.upload_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.upload_time
     *
     * @param uploadTime the value for prescription_verify_record.upload_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setUploadTime(String uploadTime) {
        this.uploadTime = uploadTime == null ? null : uploadTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.verify_time
     *
     * @return the value of prescription_verify_record.verify_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.verify_time
     *
     * @param verifyTime the value for prescription_verify_record.verify_time
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVerifyTime(String verifyTime) {
        this.verifyTime = verifyTime == null ? null : verifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record.verify_progress
     *
     * @return the value of prescription_verify_record.verify_progress
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public Integer getVerifyProgress() {
        return verifyProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record.verify_progress
     *
     * @param verifyProgress the value for prescription_verify_record.verify_progress
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    public void setVerifyProgress(Integer verifyProgress) {
        this.verifyProgress = verifyProgress;
    }
}