package org.beiyi.entity.db;

public class PrescriptionDistributionRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_distribution_record.id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_distribution_record.prescription_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    private String prescriptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_distribution_record.prescription_no
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    private String prescriptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_distribution_record.distribution_person_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    private String distributionPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_distribution_record.distribution_time
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    private String distributionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_distribution_record.id
     *
     * @return the value of prescription_distribution_record.id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_distribution_record.id
     *
     * @param id the value for prescription_distribution_record.id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_distribution_record.prescription_id
     *
     * @return the value of prescription_distribution_record.prescription_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public String getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_distribution_record.prescription_id
     *
     * @param prescriptionId the value for prescription_distribution_record.prescription_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public void setPrescriptionId(String prescriptionId) {
        this.prescriptionId = prescriptionId == null ? null : prescriptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_distribution_record.prescription_no
     *
     * @return the value of prescription_distribution_record.prescription_no
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public String getPrescriptionNo() {
        return prescriptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_distribution_record.prescription_no
     *
     * @param prescriptionNo the value for prescription_distribution_record.prescription_no
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public void setPrescriptionNo(String prescriptionNo) {
        this.prescriptionNo = prescriptionNo == null ? null : prescriptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_distribution_record.distribution_person_id
     *
     * @return the value of prescription_distribution_record.distribution_person_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public String getDistributionPersonId() {
        return distributionPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_distribution_record.distribution_person_id
     *
     * @param distributionPersonId the value for prescription_distribution_record.distribution_person_id
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public void setDistributionPersonId(String distributionPersonId) {
        this.distributionPersonId = distributionPersonId == null ? null : distributionPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_distribution_record.distribution_time
     *
     * @return the value of prescription_distribution_record.distribution_time
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public String getDistributionTime() {
        return distributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_distribution_record.distribution_time
     *
     * @param distributionTime the value for prescription_distribution_record.distribution_time
     *
     * @mbggenerated Tue Jul 31 16:47:18 CST 2018
     */
    public void setDistributionTime(String distributionTime) {
        this.distributionTime = distributionTime == null ? null : distributionTime.trim();
    }
}