package org.beiyi.entity.db;

public class PrescriptionDrugs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.prescription_verify_record_id
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String prescriptionVerifyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.sea_rainbow_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String seaRainbowCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.medical_insurance_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String medicalInsuranceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.his_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String hisNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.form
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.standard
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.pack
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String pack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.route_medication
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String routeMedication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.company_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.dosage
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.dosage_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String dosageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.dosage_frequency
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String dosageFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_quantity
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_quantity_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugQuantityUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_group
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.drug_order
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String drugOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_drugs.reimbursement_money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    private String reimbursementMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.prescription_verify_record_id
     *
     * @return the value of prescription_drugs.prescription_verify_record_id
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getPrescriptionVerifyRecordId() {
        return prescriptionVerifyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.prescription_verify_record_id
     *
     * @param prescriptionVerifyRecordId the value for prescription_drugs.prescription_verify_record_id
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setPrescriptionVerifyRecordId(String prescriptionVerifyRecordId) {
        this.prescriptionVerifyRecordId = prescriptionVerifyRecordId == null ? null : prescriptionVerifyRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_no
     *
     * @return the value of prescription_drugs.drug_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugNo() {
        return drugNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_no
     *
     * @param drugNo the value for prescription_drugs.drug_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugNo(String drugNo) {
        this.drugNo = drugNo == null ? null : drugNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.sea_rainbow_code
     *
     * @return the value of prescription_drugs.sea_rainbow_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getSeaRainbowCode() {
        return seaRainbowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.sea_rainbow_code
     *
     * @param seaRainbowCode the value for prescription_drugs.sea_rainbow_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setSeaRainbowCode(String seaRainbowCode) {
        this.seaRainbowCode = seaRainbowCode == null ? null : seaRainbowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.medical_insurance_code
     *
     * @return the value of prescription_drugs.medical_insurance_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getMedicalInsuranceCode() {
        return medicalInsuranceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.medical_insurance_code
     *
     * @param medicalInsuranceCode the value for prescription_drugs.medical_insurance_code
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setMedicalInsuranceCode(String medicalInsuranceCode) {
        this.medicalInsuranceCode = medicalInsuranceCode == null ? null : medicalInsuranceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.his_no
     *
     * @return the value of prescription_drugs.his_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getHisNo() {
        return hisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.his_no
     *
     * @param hisNo the value for prescription_drugs.his_no
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setHisNo(String hisNo) {
        this.hisNo = hisNo == null ? null : hisNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_name
     *
     * @return the value of prescription_drugs.drug_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_name
     *
     * @param drugName the value for prescription_drugs.drug_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.form
     *
     * @return the value of prescription_drugs.form
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.form
     *
     * @param form the value for prescription_drugs.form
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.standard
     *
     * @return the value of prescription_drugs.standard
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.standard
     *
     * @param standard the value for prescription_drugs.standard
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.pack
     *
     * @return the value of prescription_drugs.pack
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getPack() {
        return pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.pack
     *
     * @param pack the value for prescription_drugs.pack
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setPack(String pack) {
        this.pack = pack == null ? null : pack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.route_medication
     *
     * @return the value of prescription_drugs.route_medication
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getRouteMedication() {
        return routeMedication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.route_medication
     *
     * @param routeMedication the value for prescription_drugs.route_medication
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setRouteMedication(String routeMedication) {
        this.routeMedication = routeMedication == null ? null : routeMedication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.company_name
     *
     * @return the value of prescription_drugs.company_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.company_name
     *
     * @param companyName the value for prescription_drugs.company_name
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.dosage
     *
     * @return the value of prescription_drugs.dosage
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.dosage
     *
     * @param dosage the value for prescription_drugs.dosage
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.dosage_unit
     *
     * @return the value of prescription_drugs.dosage_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDosageUnit() {
        return dosageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.dosage_unit
     *
     * @param dosageUnit the value for prescription_drugs.dosage_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDosageUnit(String dosageUnit) {
        this.dosageUnit = dosageUnit == null ? null : dosageUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.dosage_frequency
     *
     * @return the value of prescription_drugs.dosage_frequency
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDosageFrequency() {
        return dosageFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.dosage_frequency
     *
     * @param dosageFrequency the value for prescription_drugs.dosage_frequency
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDosageFrequency(String dosageFrequency) {
        this.dosageFrequency = dosageFrequency == null ? null : dosageFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_quantity
     *
     * @return the value of prescription_drugs.drug_quantity
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugQuantity() {
        return drugQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_quantity
     *
     * @param drugQuantity the value for prescription_drugs.drug_quantity
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugQuantity(String drugQuantity) {
        this.drugQuantity = drugQuantity == null ? null : drugQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_quantity_unit
     *
     * @return the value of prescription_drugs.drug_quantity_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugQuantityUnit() {
        return drugQuantityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_quantity_unit
     *
     * @param drugQuantityUnit the value for prescription_drugs.drug_quantity_unit
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugQuantityUnit(String drugQuantityUnit) {
        this.drugQuantityUnit = drugQuantityUnit == null ? null : drugQuantityUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_group
     *
     * @return the value of prescription_drugs.drug_group
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugGroup() {
        return drugGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_group
     *
     * @param drugGroup the value for prescription_drugs.drug_group
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugGroup(String drugGroup) {
        this.drugGroup = drugGroup == null ? null : drugGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.drug_order
     *
     * @return the value of prescription_drugs.drug_order
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getDrugOrder() {
        return drugOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.drug_order
     *
     * @param drugOrder the value for prescription_drugs.drug_order
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setDrugOrder(String drugOrder) {
        this.drugOrder = drugOrder == null ? null : drugOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.money
     *
     * @return the value of prescription_drugs.money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.money
     *
     * @param money the value for prescription_drugs.money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_drugs.reimbursement_money
     *
     * @return the value of prescription_drugs.reimbursement_money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public String getReimbursementMoney() {
        return reimbursementMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_drugs.reimbursement_money
     *
     * @param reimbursementMoney the value for prescription_drugs.reimbursement_money
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    public void setReimbursementMoney(String reimbursementMoney) {
        this.reimbursementMoney = reimbursementMoney == null ? null : reimbursementMoney.trim();
    }
}