package org.beiyi.entity.db;

public class PrescriptionVerifyRecordDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_detail.id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_detail.prescription_no
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    private String prescriptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_detail.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    private String prescriptionVerifyRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_detail.drug_name
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription_verify_record_detail.error_desc
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    private String errorDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_detail.id
     *
     * @return the value of prescription_verify_record_detail.id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_detail.id
     *
     * @param id the value for prescription_verify_record_detail.id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_detail.prescription_no
     *
     * @return the value of prescription_verify_record_detail.prescription_no
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public String getPrescriptionNo() {
        return prescriptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_detail.prescription_no
     *
     * @param prescriptionNo the value for prescription_verify_record_detail.prescription_no
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public void setPrescriptionNo(String prescriptionNo) {
        this.prescriptionNo = prescriptionNo == null ? null : prescriptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_detail.prescription_verify_record_id
     *
     * @return the value of prescription_verify_record_detail.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public String getPrescriptionVerifyRecordId() {
        return prescriptionVerifyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_detail.prescription_verify_record_id
     *
     * @param prescriptionVerifyRecordId the value for prescription_verify_record_detail.prescription_verify_record_id
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public void setPrescriptionVerifyRecordId(String prescriptionVerifyRecordId) {
        this.prescriptionVerifyRecordId = prescriptionVerifyRecordId == null ? null : prescriptionVerifyRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_detail.drug_name
     *
     * @return the value of prescription_verify_record_detail.drug_name
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_detail.drug_name
     *
     * @param drugName the value for prescription_verify_record_detail.drug_name
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription_verify_record_detail.error_desc
     *
     * @return the value of prescription_verify_record_detail.error_desc
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription_verify_record_detail.error_desc
     *
     * @param errorDesc the value for prescription_verify_record_detail.error_desc
     *
     * @mbggenerated Fri Jul 20 10:21:17 CST 2018
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc == null ? null : errorDesc.trim();
    }
}