package org.beiyi.entity.db;

import java.util.Date;

public class TestCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_copy.id
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_copy.age
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_copy.name
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_copy.createTime
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_copy.id
     *
     * @return the value of test_copy.id
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_copy.id
     *
     * @param id the value for test_copy.id
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_copy.age
     *
     * @return the value of test_copy.age
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_copy.age
     *
     * @param age the value for test_copy.age
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_copy.name
     *
     * @return the value of test_copy.name
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_copy.name
     *
     * @param name the value for test_copy.name
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_copy.createTime
     *
     * @return the value of test_copy.createTime
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_copy.createTime
     *
     * @param createtime the value for test_copy.createTime
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}