package org.beiyi.entity.db;

public class TherapeuticRegimen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.dose_selection
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String doseSelection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.patient_status
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String patientStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.dosage
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.dosage_unit
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String dosageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.dosage_frequency
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String dosageFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.route_medication
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String routeMedication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column therapeutic_regimen.course_restriction
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    private String courseRestriction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.id
     *
     * @return the value of therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.id
     *
     * @param id the value for therapeutic_regimen.id
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.dose_selection
     *
     * @return the value of therapeutic_regimen.dose_selection
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDoseSelection() {
        return doseSelection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.dose_selection
     *
     * @param doseSelection the value for therapeutic_regimen.dose_selection
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDoseSelection(String doseSelection) {
        this.doseSelection = doseSelection == null ? null : doseSelection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.patient_status
     *
     * @return the value of therapeutic_regimen.patient_status
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getPatientStatus() {
        return patientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.patient_status
     *
     * @param patientStatus the value for therapeutic_regimen.patient_status
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setPatientStatus(String patientStatus) {
        this.patientStatus = patientStatus == null ? null : patientStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.dosage
     *
     * @return the value of therapeutic_regimen.dosage
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.dosage
     *
     * @param dosage the value for therapeutic_regimen.dosage
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.dosage_unit
     *
     * @return the value of therapeutic_regimen.dosage_unit
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDosageUnit() {
        return dosageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.dosage_unit
     *
     * @param dosageUnit the value for therapeutic_regimen.dosage_unit
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDosageUnit(String dosageUnit) {
        this.dosageUnit = dosageUnit == null ? null : dosageUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.dosage_frequency
     *
     * @return the value of therapeutic_regimen.dosage_frequency
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getDosageFrequency() {
        return dosageFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.dosage_frequency
     *
     * @param dosageFrequency the value for therapeutic_regimen.dosage_frequency
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setDosageFrequency(String dosageFrequency) {
        this.dosageFrequency = dosageFrequency == null ? null : dosageFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.route_medication
     *
     * @return the value of therapeutic_regimen.route_medication
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getRouteMedication() {
        return routeMedication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.route_medication
     *
     * @param routeMedication the value for therapeutic_regimen.route_medication
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setRouteMedication(String routeMedication) {
        this.routeMedication = routeMedication == null ? null : routeMedication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column therapeutic_regimen.course_restriction
     *
     * @return the value of therapeutic_regimen.course_restriction
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public String getCourseRestriction() {
        return courseRestriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column therapeutic_regimen.course_restriction
     *
     * @param courseRestriction the value for therapeutic_regimen.course_restriction
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    public void setCourseRestriction(String courseRestriction) {
        this.courseRestriction = courseRestriction == null ? null : courseRestriction.trim();
    }
}