package org.beiyi.entity.db;

public class UserSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.user_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.section_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.username
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.section_name
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    private String sectionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.id
     *
     * @return the value of bysy_user_section.id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.id
     *
     * @param id the value for bysy_user_section.id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.user_id
     *
     * @return the value of bysy_user_section.user_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.user_id
     *
     * @param userId the value for bysy_user_section.user_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.section_id
     *
     * @return the value of bysy_user_section.section_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.section_id
     *
     * @param sectionId the value for bysy_user_section.section_id
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.username
     *
     * @return the value of bysy_user_section.username
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.username
     *
     * @param username the value for bysy_user_section.username
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.section_name
     *
     * @return the value of bysy_user_section.section_name
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.section_name
     *
     * @param sectionName the value for bysy_user_section.section_name
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }
}