package org.beiyi.entity.db;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.username
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.password
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.phone_no
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.email
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.create_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.login_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user.user_real_name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    private String userRealName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.id
     *
     * @return the value of bysy_user.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.id
     *
     * @param id the value for bysy_user.id
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.username
     *
     * @return the value of bysy_user.username
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.username
     *
     * @param username the value for bysy_user.username
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.password
     *
     * @return the value of bysy_user.password
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.password
     *
     * @param password the value for bysy_user.password
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.phone_no
     *
     * @return the value of bysy_user.phone_no
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.phone_no
     *
     * @param phoneNo the value for bysy_user.phone_no
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.email
     *
     * @return the value of bysy_user.email
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.email
     *
     * @param email the value for bysy_user.email
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.create_time
     *
     * @return the value of bysy_user.create_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.create_time
     *
     * @param createTime the value for bysy_user.create_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.login_time
     *
     * @return the value of bysy_user.login_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.login_time
     *
     * @param loginTime the value for bysy_user.login_time
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user.user_real_name
     *
     * @return the value of bysy_user.user_real_name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user.user_real_name
     *
     * @param userRealName the value for bysy_user.user_real_name
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName == null ? null : userRealName.trim();
    }
}