package org.beiyi.entity.db;

public class UserSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.user_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bysy_user_section.section_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    private String sectionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.id
     *
     * @return the value of bysy_user_section.id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.id
     *
     * @param id the value for bysy_user_section.id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.user_id
     *
     * @return the value of bysy_user_section.user_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.user_id
     *
     * @param userId the value for bysy_user_section.user_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bysy_user_section.section_id
     *
     * @return the value of bysy_user_section.section_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bysy_user_section.section_id
     *
     * @param sectionId the value for bysy_user_section.section_id
     *
     * @mbggenerated Tue Jul 24 10:12:33 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }
}