package org.beiyi.dao;

import org.beiyi.entity.db.AtcBelongTo;

public interface AtcBelongToMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insert(AtcBelongTo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insertSelective(AtcBelongTo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    AtcBelongTo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKeySelective(AtcBelongTo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_belong_to
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKey(AtcBelongTo record);
}