package org.beiyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.beiyi.entity.db.AtcCode;
import org.beiyi.entity.verify.ATCCode;

public interface AtcCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    int insert(AtcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    int insertSelective(AtcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    AtcCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    int updateByPrimaryKeySelective(AtcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_atc_code
     *
     * @mbggenerated Wed Jul 04 15:15:03 CST 2018
     */
    int updateByPrimaryKey(AtcCode record);
    
    
    List<AtcCode> selectByChName(@Param(value="chName") String chName);

	AtcCode findByAtcNo(@Param(value="atcNo") String atcNo);

	List<AtcCode> selectAll();
}