package org.beiyi.dao;

import org.beiyi.entity.db.AtcConflict;

public interface AtcConflictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insert(AtcConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insertSelective(AtcConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    AtcConflict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKeySelective(AtcConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atc_conflict
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKey(AtcConflict record);
}