package org.beiyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.beiyi.entity.db.Disease;

public interface DiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    int insert(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    int insertSelective(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    Disease selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    int updateByPrimaryKeySelective(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Thu Jul 05 17:16:32 CST 2018
     */
    int updateByPrimaryKey(Disease record);

	Disease selectByDiseaseName(@Param(value="disName") String disName);

	List<Disease> findAll();
}