package org.beiyi.dao;

import org.beiyi.entity.db.DiseaseIcd10;

public interface DiseaseIcd10Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    int insert(DiseaseIcd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    int insertSelective(DiseaseIcd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    DiseaseIcd10 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    int updateByPrimaryKeySelective(DiseaseIcd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_icd10
     *
     * @mbggenerated Tue Jul 10 17:04:15 CST 2018
     */
    int updateByPrimaryKey(DiseaseIcd10 record);
}