package org.beiyi.dao;

import java.util.List;

import org.beiyi.entity.db.Icd10;

public interface Icd10Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    int insert(Icd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    int insertSelective(Icd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    Icd10 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    int updateByPrimaryKeySelective(Icd10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_icd10
     *
     * @mbggenerated Wed Jul 04 14:52:37 CST 2018
     */
    int updateByPrimaryKey(Icd10 record);

	List<Icd10> findByIcd10(Icd10 icd10);
}