package org.beiyi.dao;

import org.beiyi.entity.db.Instructions;

public interface InstructionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insert(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insertSelective(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    Instructions selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKeySelective(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKey(Instructions record);
}