package org.beiyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.beiyi.entity.db.InstructionsCategory;

public interface InstructionsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    int insert(InstructionsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Thu Jul 12 18:26:18 CST 2018
     */
    int insertSelective(InstructionsCategory record);

	List<InstructionsCategory> selectByCombinationStandardName(
			@Param(value="combinationStandardName")String combinationStandardName);
}