package org.beiyi.dao;

import org.beiyi.entity.db.InstructionsCrowd;

public interface InstructionsCrowdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    int insert(InstructionsCrowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    int insertSelective(InstructionsCrowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    InstructionsCrowd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    int updateByPrimaryKeySelective(InstructionsCrowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_crowd
     *
     * @mbggenerated Fri Jul 13 11:24:13 CST 2018
     */
    int updateByPrimaryKey(InstructionsCrowd record);

	InstructionsCrowd findByCondition(InstructionsCrowd condition);
}