package org.beiyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.beiyi.entity.db.InstructionsCategory;

public interface InstructionsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    int insert(InstructionsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    int insertSelective(InstructionsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    InstructionsCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    int updateByPrimaryKeySelective(InstructionsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions_category
     *
     * @mbggenerated Fri Jul 13 10:02:06 CST 2018
     */
    int updateByPrimaryKey(InstructionsCategory record);
    
    
    List<InstructionsCategory> selectByCombinationStandardName(@Param(value="combinationStandardName")String combinationStandardName);
}