package org.beiyi.dao;

import java.util.List;

import org.beiyi.entity.db.InstructionIndication;

public interface InstructionIndicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    int insert(InstructionIndication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    int insertSelective(InstructionIndication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    InstructionIndication selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    int updateByPrimaryKeySelective(InstructionIndication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Thu Jul 05 18:01:03 CST 2018
     */
    int updateByPrimaryKey(InstructionIndication record);

	InstructionIndication selectByInstructionIndication(
			InstructionIndication instructionIndication);

	List<InstructionIndication> findAll();
	/**
	 * 获取适应症列表
	 * @param instructionIndication
	 * @return
	 */
	List<InstructionIndication> findIndications(
			InstructionIndication instructionIndication);
}