package org.beiyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.beiyi.entity.db.InstructionComponent;
import org.beiyi.entity.db.Instructions;
import org.beiyi.entity.verify.Instruction;

public interface InstructionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    int insert(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    int insertSelective(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    Instructions selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(Instructions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructions
     *
     * @mbggenerated Thu Jul 05 12:09:09 CST 2018
     */
    int updateByPrimaryKey(Instructions record);

	List<Instructions> selectByCommodityNameAndCommonName(@Param(value="commodityName") String commodityName,@Param(value="commonName") String commonName);
}