package org.beiyi.dao;

import org.beiyi.entity.db.InstructionIndication;

public interface InstructionIndicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insert(InstructionIndication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_indication
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insertSelective(InstructionIndication record);
}