package org.beiyi.dao;

import org.beiyi.entity.db.InstructionComponentAtc;

public interface InstructionComponentAtcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    int insert(InstructionComponentAtc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    int insertSelective(InstructionComponentAtc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    InstructionComponentAtc selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    int updateByPrimaryKeySelective(InstructionComponentAtc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instruction_component_atc
     *
     * @mbggenerated Thu Jul 05 14:29:40 CST 2018
     */
    int updateByPrimaryKey(InstructionComponentAtc record);
}