package org.beiyi.dao;

import java.util.List;

import org.beiyi.entity.db.PrescriptionDrugs;

public interface PrescriptionDrugsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_drugs
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    int insert(PrescriptionDrugs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_drugs
     *
     * @mbggenerated Mon Jul 16 14:49:01 CST 2018
     */
    int insertSelective(PrescriptionDrugs record);

	List<PrescriptionDrugs> getPagedList(PrescriptionDrugs record);
}