package org.beiyi.dao;

import java.util.List;

import org.beiyi.entity.db.PrescriptionVerifyRecord;
import org.beiyi.entity.db.pageBean.Prescription;

public interface PrescriptionVerifyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    int insert(PrescriptionVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    int insertSelective(PrescriptionVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    PrescriptionVerifyRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    int updateByPrimaryKeySelective(PrescriptionVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_verify_record
     *
     * @mbggenerated Mon Jul 16 15:29:38 CST 2018
     */
    int updateByPrimaryKey(PrescriptionVerifyRecord record);
    
    int updateByPrescriptionNo(PrescriptionVerifyRecord record);
    
    int updateVerifyProgressByPrescriptionNo(PrescriptionVerifyRecord record);
    
    List<PrescriptionVerifyRecord> getPagedList(PrescriptionVerifyRecord record);
    
    List<Prescription> getPrescriptionPagedList();
}