package org.beiyi.dao;

import org.beiyi.entity.db.TestCopy;

public interface TestCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    int insert(TestCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    int insertSelective(TestCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    TestCopy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    int updateByPrimaryKeySelective(TestCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_copy
     *
     * @mbggenerated Wed Aug 01 15:03:05 CST 2018
     */
    int updateByPrimaryKey(TestCopy record);
}