package org.beiyi.dao;

import org.beiyi.entity.db.TherapeuticRegimen;

public interface TherapeuticRegimenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insert(TherapeuticRegimen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int insertSelective(TherapeuticRegimen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    TherapeuticRegimen selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKeySelective(TherapeuticRegimen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table therapeutic_regimen
     *
     * @mbggenerated Wed Jul 04 18:19:19 CST 2018
     */
    int updateByPrimaryKey(TherapeuticRegimen record);
}