package org.beiyi.dao;

import org.beiyi.entity.db.UserSection;

public interface UserSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    int insert(UserSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    int insertSelective(UserSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    UserSection selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    int updateByPrimaryKeySelective(UserSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bysy_user_section
     *
     * @mbggenerated Fri Jul 20 14:25:17 CST 2018
     */
    int updateByPrimaryKey(UserSection record);
}